name: Run tests

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --editable .
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -s
